enum ActionType {
  GET_MEMBERS_START = 'GITHUB/GET_MEMBERS_START',
  GET_MEMBERS_SUCCEED = 'GITHUB/GET_MEMBERS_SUCCEED',
  GET_MEMBERS_FAIL = 'GITHUB/GET_MEMBERS_FAIL',
}

export default ActionType;
